CREATE TABLE trd.trd_shopping_loan_order
(
    id bigint(32) PRIMARY KEY NOT NULL COMMENT '表id' AUTO_INCREMENT,
    product_freeze_no varchar(32) COMMENT '商品系统冻结编号',
    order_amount int(11) NOT NULL COMMENT '订单金额，单位为分',
    fee_amount int(11) NOT NULL COMMENT '订单服务费',
    interest_amount int(11) COMMENT '订单利息',
    payment_amount int(11) DEFAULT '0' COMMENT '实际到账金额，单位为分',
    repayment_amount int(11) DEFAULT '0' NOT NULL COMMENT '应还金额',
    term int(8) NOT NULL COMMENT '期数',
    term_unit varchar(20) COMMENT '期数单位',
    term_rate decimal(10,4) DEFAULT '0.0000' NOT NULL COMMENT '期利率',
    product_id bigint(32) NOT NULL COMMENT '产品id',
    product_category int(4) NOT NULL COMMENT '产品类型  (1:小额   2:大额  3:商城)',
    is_depository varchar(2) DEFAULT '1' COMMENT '是否存管',
    user_type tinyint(1) DEFAULT '0' NOT NULL COMMENT '是否是老用户：0、新用户；1；老用户',
    status varchar(32) DEFAULT '0' NOT NULL,
    trace_no varchar(32) NOT NULL COMMENT '订单系统追踪号',
    user_id bigint(32) NOT NULL COMMENT '用户id',
    user_idcard_type varchar(20) COMMENT '证件类型',
    user_idcard_no varchar(32) COMMENT '证件号',
    user_bank_card_id bigint(32) COMMENT '用户银行卡号id',
    bank_name varchar(32) COMMENT '银行名称',
    bank_card_no_last_four varchar(32) COMMENT '银行卡号后4位',
    user_phone varchar(11) NOT NULL COMMENT '用户手机号',
    user_name varchar(255) NOT NULL COMMENT '真实姓名',
    source varchar(2) DEFAULT '1' NOT NULL COMMENT '订单来源：01、商城系统',
    terminal varchar(2) NOT NULL COMMENT '终端类型 01 ios ,02 android, 03 h5',
    uk_token varchar(32) NOT NULL COMMENT '防并发的token',
    created_at datetime NOT NULL COMMENT '创建时间(立即申请时间)',
    created_user varchar(32) DEFAULT 'sys' COMMENT '创建人',
    updated_at datetime NOT NULL COMMENT '更新时间',
    updated_user varchar(32) DEFAULT 'sys' COMMENT '更新人',
    specification_json varchar(50) COMMENT '商品规格json,如 {11:24, 12:28, 13:32}',
    specification_desc varchar(50) NOT NULL COMMENT '商品规格json描述||如土豪金||128GB||港版',
    remark varchar(2000) COMMENT '备注',
    data_valid tinyint(1) DEFAULT '1' NOT NULL COMMENT '数据有效性 0 无效  1 有效'
) AUTO_INCREMENT=9000000000;

CREATE TABLE trd.trd_shopping_logistics_order
(
    id bigint(32) PRIMARY KEY NOT NULL COMMENT '表id' AUTO_INCREMENT,
    shopping_loan_order_id bigint(32) NOT NULL COMMENT '商品商品系统订单号',
    receive_province varchar(32) NOT NULL COMMENT '收货人省份',
    receive_city varchar(32) NOT NULL COMMENT '收货人城市',
    receive_area varchar(32) NOT NULL COMMENT '收货人区县',
    receive_addr varchar(124) NOT NULL COMMENT '收货人详细地址',
    receive_post_no varchar(32) COMMENT '收货人邮政编码',
    receive_username varchar(32) NOT NULL COMMENT '收货人姓名',
    receive_mobile varchar(11) NOT NULL COMMENT '收货人手机号',
    logistics_company varchar(32) COMMENT '物流公司名称',
    logistics_no varchar(32) COMMENT '物流编号',
    logistics_phone varchar(11) COMMENT '物流公司电话',
    status varchar(32) DEFAULT '0' NOT NULL,
    created_at datetime NOT NULL COMMENT '创建时间',
    created_user varchar(32) DEFAULT 'sys' COMMENT '创建人',
    updated_at datetime NOT NULL COMMENT '更新时间',
    updated_user varchar(32) DEFAULT 'sys' COMMENT '更新人',
    data_valid tinyint(1) DEFAULT '1' NOT NULL COMMENT '数据有效性 0 无效  1 有效',
    send_province varchar(32) COMMENT '发货人省份',
    send_city varchar(32) COMMENT '发货人城市',
    send_area varchar(32) COMMENT '发货人区县',
    send_addr varchar(32) COMMENT '发货人详细地址',
    send_post_no varchar(32) COMMENT '发货人邮政编码',
    send_username varchar(32) COMMENT '发货人姓名',
    send_mobile varchar(11) COMMENT '发货人手机号',
    order_type varchar(32) COMMENT '物流订单类型',
    logistics_price int(11) COMMENT '邮递费用',
    send_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '发货时间',
    vender_id varchar(32) COMMENT '供应商id',
    vender_name varchar(32) COMMENT '供应商名称'
);

CREATE TABLE trd.trd_shopping_product_order
(
    id bigint(32) PRIMARY KEY NOT NULL COMMENT '表id' AUTO_INCREMENT,
    shopping_loan_order_id bigint(32) NOT NULL COMMENT '商品商品系统订单号',
    product_id varchar(32) NOT NULL COMMENT '产品编号',
    product_price int(8) NOT NULL COMMENT '产品价格',
    product_name varchar(100) NOT NULL COMMENT '产品名称',
    product_category varchar(32) NOT NULL COMMENT '产品类型  (1:金融产品)',
    status varchar(32) DEFAULT '0' NOT NULL,
    created_at datetime NOT NULL COMMENT '创建时间',
    created_user varchar(32) DEFAULT 'sys' COMMENT '创建人',
    updated_at datetime NOT NULL COMMENT '更新时间',
    updated_user varchar(32) DEFAULT 'sys' COMMENT '更新人',
    data_valid tinyint(1) DEFAULT '1' NOT NULL COMMENT '数据有效性 0 无效  1 有效'
);

CREATE TABLE trd.trd_shopping_user_addr
(
    id bigint(32) PRIMARY KEY NOT NULL COMMENT '表id' AUTO_INCREMENT,
    user_id bigint(32) NOT NULL COMMENT '用户ID',
    province varchar(32) NOT NULL COMMENT '省份',
    city varchar(32) NOT NULL COMMENT '城市',
    area varchar(32) NOT NULL COMMENT '区县',
    detail_addr varchar(128) NOT NULL COMMENT '详细地址',
    post_no varchar(32) COMMENT '邮政编码',
    username varchar(32) NOT NULL COMMENT '姓名',
    mobile varchar(11) NOT NULL COMMENT '手机号',
    is_default tinyint(1) DEFAULT '1' NOT NULL COMMENT '是否默认地址',
    created_at datetime NOT NULL COMMENT '创建时间',
    updated_at datetime NOT NULL COMMENT '更新时间',
    remark varchar(2000) COMMENT '备注',
    data_valid tinyint(1) DEFAULT '1' NOT NULL COMMENT '数据有效性 0 无效  1 有效'
);